"""
panel_regression.py

This script performs the Panel Regressions outlined in the term paper proposal.
It reads the fully merged final_analysis_panel.csv (which contains CRSP, Compustat, and Fama-French data)
and the categorized text scores.

Prerequisites:
- pip install pandas numpy statsmodels linearmodels
- final_analysis_panel.csv (Generated by market_data_pipeline.py)
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
from linearmodels.panel import PanelOLS
import os

# --- 1. Load Data ---
# We use the final sterilized dataset from market_data_pipeline.py
panel_data_path = r"C:\Users\Admin\Downloads\New folder\final_analysis_panel.csv"

if not os.path.exists(panel_data_path):
    print(f"Error: Missing {panel_data_path}.")
    print("Please run market_data_pipeline.py first to generate the merged financial/nlp dataset.")
    exit()

df = pd.read_csv(panel_data_path)

# Ensure the category columns exist (if market_data_pipeline merged the raw NLP data, 
# we need to calculate the categories here, or assume they are merged in)
# Let's calculate them dynamically just to be safe if they aren't there!
CATEGORIES = {
    "Core_Cloud_and_Data_Center": [
        "data_center_norm", "server_farm_norm", "colocation_norm", "hyperscaler_norm", 
        "edge_computing_norm", "cloud_infrastructure_norm", "data_warehousing_norm", 
        "cloud_computing_norm", "gpu_cluster_norm", "infrastructure_as_a_service_norm"
    ],
    "Cyber_and_Resilience_Risk": [
        "cybersecurity_infrastructure_norm", "disaster_recovery_norm", 
        "data_sovereignty_norm", "power_usage_effectiveness_norm"
    ]
}

for cat, cols in CATEGORIES.items():
    cat_col = f"{cat}_category_score"
    if cat_col not in df.columns:
        valid_cols = [c for c in cols if c in df.columns]
        if valid_cols:
            df[cat_col] = df[valid_cols].sum(axis=1)
        else:
            df[cat_col] = 0

# Filter for the timeframe (2000-2025) as per your request
df = df[(df['fyear'] >= 2000) & (df['fyear'] <= 2025)]

# --- 2. Prepare Variables ---
# Variables we need for the panel regression
# market_data_pipeline.py already calculates 'Excess_Return' (Return - Risk Free rate)
vars_of_interest = [
    'Excess_Return', 
    'Core_Cloud_and_Data_Center_category_score',
    'Cyber_and_Resilience_Risk_category_score',
    'Size', 'ROA', 'Leverage'
]

available_vars = [v for v in vars_of_interest if v in df.columns]
df = df.dropna(subset=available_vars)

if 'Excess_Return' in available_vars and 'Core_Cloud_and_Data_Center_category_score' in available_vars:
    # Set multi-index for PanelOLS (Entity/Firm and Time/Year)
    df = df.set_index(['cik', 'fyear'])

    # --- Model 1: Determinants of Data Center Exposure ---
    print("\n" + "="*60)
    print("MODEL 1: Determinants of Data Center Exposure")
    print("="*60)
    exog_vars1 = ['Size', 'ROA', 'Leverage']
    if all(v in df.columns for v in exog_vars1):
        exog1 = sm.add_constant(df[exog_vars1])
        mod1 = PanelOLS(df['Core_Cloud_and_Data_Center_category_score'], exog1, entity_effects=True, time_effects=True)
        res1 = mod1.fit(cov_type='clustered', cluster_entity=True)
        print(res1)

    # --- Model 2: Performance Benefits ---
    print("\n" + "="*60)
    print("MODEL 2: Performance Benefits (Excess Returns ~ Data Center)")
    print("="*60)
    exog_vars2 = ['Core_Cloud_and_Data_Center_category_score', 'Size', 'ROA', 'Leverage']
    if all(v in df.columns for v in exog_vars2):
        exog2 = sm.add_constant(df[exog_vars2])
        mod2 = PanelOLS(df['Excess_Return'], exog2, entity_effects=True, time_effects=True)
        res2 = mod2.fit(cov_type='clustered', cluster_entity=True)
        print(res2)

    # --- Model 3: Risk Premium (Cyber Risk Pricing) ---
    print("\n" + "="*60)
    print("MODEL 3: Risk Premium (Excess Returns ~ Data Center + Cyber Risk)")
    print("="*60)
    exog_vars3 = ['Core_Cloud_and_Data_Center_category_score', 'Cyber_and_Resilience_Risk_category_score', 'Size', 'ROA', 'Leverage']
    if all(v in df.columns for v in exog_vars3):
        exog3 = sm.add_constant(df[exog_vars3])
        mod3 = PanelOLS(df['Excess_Return'], exog3, entity_effects=True, time_effects=True)
        res3 = mod3.fit(cov_type='clustered', cluster_entity=True)
        print(res3)
else:
    print("Data variables are missing. Ensure market_data_pipeline.py ran successfully.")
